# Generate completions/ from the binary's own help (#392).
#
# Same argument as build-reference.ps1 (#209): the binary is the only thing
# that knows its own commands and flags, so a completion script written beside
# it is a second copy that drifts, and the drift is invisible until someone
# presses TAB and gets nothing.
#
# So this asks the binary. Commands and subcommands come from `skrog help
# --json`; flags come from each command's own `--help` output, which is Go's
# flag.PrintDefaults and therefore a stable shape ("  -name" at the start of a
# line). Nothing here knows what any command does.
#
#   pwsh -File scripts/build-completions.ps1          # regenerate
#   pwsh -File scripts/build-completions.ps1 -Check   # fail if it would change
#
# -Check is what CI runs: adding a flag without regenerating should fail in
# review, not ship completions that describe the previous release.
[CmdletBinding()]
param(
    [switch]$Check,
    # Use an existing binary instead of building one. The generated text must
    # come from the working tree, so the default is to build.
    [string]$Exe
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path $PSScriptRoot -Parent
$outDir = Join-Path $repo 'completions'

Push-Location $repo
try {
    if (-not $Exe) {
        $Exe = Join-Path ([IO.Path]::GetTempPath()) 'skrog-completions.exe'
        Write-Host "building skrog..." -ForegroundColor DarkGray
        # No version stamp: completions must not change just because they were
        # generated from a tagged build rather than a working tree.
        & go build -o $Exe ./cmd/skrog
        if ($LASTEXITCODE -ne 0) { throw "go build failed" }
    }

    $index = & $Exe help --json | ConvertFrom-Json
    if (-not $index) { throw "``skrog help --json`` returned nothing" }

    # `--help` prints usage on stderr and exits 2 (the usage code), because for
    # every other invocation that text accompanies a mistake. Both are expected
    # here, so stderr is merged in and the exit code is not treated as failure.
    #
    # A command that rejects `--help` as an unknown subcommand (`skrog cli`)
    # simply yields no flags, which is correct: its flags live on its
    # subcommands, and offering the parent's would be a lie.
    function Get-Flags([string]$command) {
        $text = & $Exe $command --help 2>&1 | Out-String
        $flags = [System.Collections.Generic.List[string]]::new()
        foreach ($line in ($text -split "`r?`n")) {
            # flag.PrintDefaults writes "  -name" or "  -name value-type".
            if ($line -match '^\s{1,4}-([a-zA-Z][a-zA-Z0-9-]*)\b') {
                $f = "--$($Matches[1])"
                if (-not $flags.Contains($f)) { $flags.Add($f) }
            }
        }
        return , $flags.ToArray()
    }

    $commands = @{}
    foreach ($c in $index) {
        $commands[$c.name] = [pscustomobject]@{
            Name = $c.name
            # Filtered, not just wrapped: `subcommands` is omitempty, and in
            # PowerShell @($null) is an array of one null, which would emit an
            # empty subs entry for every command that has none.
            Subs  = @($c.subcommands | Where-Object { $_ })
            Flags = Get-Flags $c.name
        }
    }
    $names = $index.name

    # ---- PowerShell -------------------------------------------------------
    # Register-ArgumentCompleter is the native mechanism; the script is meant
    # to be dot-sourced from a profile.
    $ps = [System.Text.StringBuilder]::new()
    $null = $ps.AppendLine(@'
# skrog completions for PowerShell.
#
# GENERATED by scripts/build-completions.ps1 from the binary's own --help.
# Do not edit: CI regenerates this and fails if it differs.
#
# Install by dot-sourcing from your profile ($PROFILE):
#   . path\to\skrog.ps1
# Or, if skrog is on PATH, append it once:
#   skrog completions powershell >> $PROFILE     # not a command yet -- copy the file

$script:SkrogCommands = @(
'@)
    foreach ($n in $names) { $null = $ps.AppendLine("    '$n'") }
    $null = $ps.AppendLine(')')
    $null = $ps.AppendLine()

    $null = $ps.AppendLine('$script:SkrogSubcommands = @{')
    foreach ($n in $names) {
        $c = $commands[$n]
        if ($c.Subs.Count -gt 0) {
            $quoted = ($c.Subs | ForEach-Object { "'$_'" }) -join ', '
            $null = $ps.AppendLine("    '$n' = @($quoted)")
        }
    }
    $null = $ps.AppendLine('}')
    $null = $ps.AppendLine()

    $null = $ps.AppendLine('$script:SkrogFlags = @{')
    foreach ($n in $names) {
        $c = $commands[$n]
        if ($c.Flags.Count -gt 0) {
            $quoted = ($c.Flags | ForEach-Object { "'$_'" }) -join ', '
            $null = $ps.AppendLine("    '$n' = @($quoted)")
        }
    }
    $null = $ps.AppendLine('}')
    $null = $ps.AppendLine()

    $null = $ps.AppendLine(@'
# Values that only the machine knows: config keys, saved profiles, registered
# remotes, snapshots. Asking skrog at completion time beats baking a list that
# is wrong the moment someone saves a profile.
#
# Every one of these goes through --json rather than parsing the human output:
# the text listings carry an active marker, and their "no profiles yet"
# sentence is a sentence, so text parsing offered "no" as a completion.
#
# All are read-only and none starts the engine. Failures are swallowed: a
# completion that throws is worse than one that offers nothing.
function Get-SkrogDynamic([string]$kind) {
    try {
        switch ($kind) {
            'config-key' {
                $j = & skrog config --json 2>$null | ConvertFrom-Json
                $j.settings.PSObject.Properties.Name
            }
            'profile'  { (& skrog profile --json 2>$null | ConvertFrom-Json).profiles.name }
            'remote'   { (& skrog remote --json 2>$null | ConvertFrom-Json).remotes.name }
            'snapshot' { (& skrog snapshot list --json 2>$null | ConvertFrom-Json).name }
        }
    } catch { @() }
}

Register-ArgumentCompleter -Native -CommandName skrog -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    # Everything before the cursor, minus the executable itself.
    $tokens = @($commandAst.CommandElements | Select-Object -Skip 1 |
        ForEach-Object { $_.ToString() })
    # The word being typed is not yet a settled token. The Count -eq 1 case is
    # separate on purpose: $tokens[0..-1] does not produce an empty array, it
    # wraps and yields the element twice, which made `skrog sn<TAB>` offer
    # nothing because "sn" looked like a settled command name.
    if ($wordToComplete -and $tokens.Count -gt 0 -and $tokens[-1] -eq $wordToComplete) {
        if ($tokens.Count -eq 1) { $tokens = @() }
        else { $tokens = $tokens[0..($tokens.Count - 2)] }
    }
    $positional = @($tokens | Where-Object { $_ -notlike '-*' })
    $command = if ($positional.Count -gt 0) { $positional[0] } else { $null }
    $sub = if ($positional.Count -gt 1) { $positional[1] } else { $null }

    $candidates = @()
    if (-not $command) {
        $candidates = $script:SkrogCommands
    } else {
        if ($wordToComplete -like '-*') {
            $candidates = $script:SkrogFlags[$command]
        } else {
            # A value position: offer what this machine actually has.
            $dynamic = switch ("$command $sub") {
                'config get'      { Get-SkrogDynamic 'config-key' }
                'config set'      { if ($positional.Count -le 2) { Get-SkrogDynamic 'config-key' } }
                'profile switch'  { Get-SkrogDynamic 'profile' }
                'profile show'    { Get-SkrogDynamic 'profile' }
                'snapshot restore' { Get-SkrogDynamic 'snapshot' }
                'snapshot delete' { Get-SkrogDynamic 'snapshot' }
                'remote use'      { @(Get-SkrogDynamic 'remote') + 'local' }
                'remote test'     { Get-SkrogDynamic 'remote' }
                default { $null }
            }
            if ($null -ne $dynamic) {
                $candidates = $dynamic
            } elseif (-not $sub) {
                $candidates = $script:SkrogSubcommands[$command]
            }
        }
    }

    $candidates |
        Where-Object { $_ -and $_.StartsWith($wordToComplete, [StringComparison]::OrdinalIgnoreCase) } |
        Sort-Object -Unique |
        ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
}
'@)

    # ---- bash -------------------------------------------------------------
    $bash = [System.Text.StringBuilder]::new()
    $null = $bash.AppendLine(@'
# skrog completions for bash.
#
# GENERATED by scripts/build-completions.ps1 from the binary's own --help.
# Do not edit: CI regenerates this and fails if it differs.
#
# Install:
#   source path/to/skrog.bash
# or drop it in /etc/bash_completion.d/ (or ~/.local/share/bash-completion/completions/skrog).
#
# Useful from Git Bash and from a wsl-integrate'd distro, where skrog.exe is on
# PATH and the engine is the same one.

_skrog() {
    local cur prev words cword
    cur="${COMP_WORDS[COMP_CWORD]}"

    local commands subs flags
'@)
    $null = $bash.AppendLine("    commands=`"$($names -join ' ')`"")
    $null = $bash.AppendLine()
    $null = $bash.AppendLine('    # First positional is the command; the second, if any, the subcommand.')
    $null = $bash.AppendLine(@'
    local command="" sub="" i seen=0
    for ((i = 1; i < COMP_CWORD; i++)); do
        case "${COMP_WORDS[i]}" in
            -*) continue ;;
        esac
        if [ "$seen" -eq 0 ]; then
            command="${COMP_WORDS[i]}"
            seen=1
        elif [ -z "$sub" ]; then
            sub="${COMP_WORDS[i]}"
        fi
    done

    if [ -z "$command" ]; then
        mapfile -t COMPREPLY < <(compgen -W "$commands" -- "$cur")
        return
    fi

    if [[ "$cur" == -* ]]; then
        case "$command" in
'@)
    foreach ($n in $names) {
        $c = $commands[$n]
        if ($c.Flags.Count -gt 0) {
            $null = $bash.AppendLine("            $n) flags=`"$($c.Flags -join ' ')`" ;;")
        }
    }
    $null = $bash.AppendLine(@'
            *) flags="" ;;
        esac
        mapfile -t COMPREPLY < <(compgen -W "$flags" -- "$cur")
        return
    fi

    # Values only the machine knows. Read-only, none starts the engine.
    #
    # Parsed from --json rather than the human listings: those carry an active
    # marker, and their "no profiles yet" sentence is a sentence, so text
    # parsing offered "no" as a completion. Without a JSON parser to hand this
    # uses grep for the name fields, which is enough for a flat list of names
    # and avoids making jq a requirement.
    local dynamic=""
    _skrog_names() { grep -o '"name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"\([^"]*\)"$/\1/'; }
    case "$command $sub" in
        "config get"|"config set")
            dynamic=$(skrog config --json 2>/dev/null \
                | sed -n '/"settings"/,$p' \
                | grep -o '"[a-z][a-z0-9.-]*"[[:space:]]*:' | sed 's/"\(.*\)"[[:space:]]*:/\1/') ;;
        "profile switch"|"profile show"|"profile delete")
            dynamic=$(skrog profile --json 2>/dev/null | _skrog_names) ;;
        "snapshot restore"|"snapshot delete")
            dynamic=$(skrog snapshot list --json 2>/dev/null | _skrog_names) ;;
        "remote use")
            dynamic="local $(skrog remote --json 2>/dev/null | _skrog_names)" ;;
        "remote test"|"remote remove")
            dynamic=$(skrog remote --json 2>/dev/null | _skrog_names) ;;
    esac
    if [ -n "$dynamic" ]; then
        mapfile -t COMPREPLY < <(compgen -W "$dynamic" -- "$cur")
        return
    fi

    if [ -z "$sub" ]; then
        case "$command" in
'@)
    foreach ($n in $names) {
        $c = $commands[$n]
        if ($c.Subs.Count -gt 0) {
            $null = $bash.AppendLine("            $n) subs=`"$($c.Subs -join ' ')`" ;;")
        }
    }
    $null = $bash.AppendLine(@'
            *) subs="" ;;
        esac
        mapfile -t COMPREPLY < <(compgen -W "$subs" -- "$cur")
    fi
}

complete -F _skrog skrog
complete -F _skrog skrog.exe
'@)

    # Normalized to LF and written whole, so the files are identical whatever a
    # contributor's autocrlf setting is - otherwise -Check fails on Windows for
    # reasons that have nothing to do with the help text.
    $files = @{
        'skrog.ps1'  = $ps.ToString().Replace("`r`n", "`n").TrimEnd() + "`n"
        'skrog.bash' = $bash.ToString().Replace("`r`n", "`n").TrimEnd() + "`n"
    }

    if ($Check) {
        foreach ($name in $files.Keys | Sort-Object) {
            $path = Join-Path $outDir $name
            if (-not (Test-Path $path)) {
                Write-Host "completions/$name does not exist; run scripts/build-completions.ps1" -ForegroundColor Red
                exit 1
            }
            $current = [IO.File]::ReadAllText($path).Replace("`r`n", "`n")
            if ($current -ne $files[$name]) {
                Write-Host "completions/$name is out of date with the binary's --help output." -ForegroundColor Red
                Write-Host "Run: pwsh -File scripts/build-completions.ps1" -ForegroundColor Red
                exit 1
            }
        }
        Write-Host "completions/ matches the binary" -ForegroundColor Green
        exit 0
    }

    New-Item -ItemType Directory -Force $outDir | Out-Null
    foreach ($name in $files.Keys | Sort-Object) {
        [IO.File]::WriteAllText((Join-Path $outDir $name), $files[$name])
    }
    Write-Host "wrote completions/ ($($index.Count) commands)" -ForegroundColor Green
} finally {
    Pop-Location
}
