# skrog completions for bash.
#
# GENERATED by scripts/build-completions.ps1 from the binary's own --help.
# Do not edit: CI regenerates this and fails if it differs.
#
# Install:
#   source path/to/skrog.bash
# or drop it in /etc/bash_completion.d/ (or ~/.local/share/bash-completion/completions/skrog).
#
# Useful from Git Bash and from a wsl-integrate'd distro, where skrog.exe is on
# PATH and the engine is the same one.

_skrog() {
    local cur prev words cword
    cur="${COMP_WORDS[COMP_CWORD]}"

    local commands subs flags
    commands="audit autostart bundle cache cli compact config doctor enable-gpu engine healthcheck install lock logs migrate prewarm policy profile proxy prune relocate remote reset restart runner serve snapshot start status stop supervise top uninstall upgrade wsl-integrate wsl-config version"

    # First positional is the command; the second, if any, the subcommand.
    local command="" sub="" i seen=0
    for ((i = 1; i < COMP_CWORD; i++)); do
        case "${COMP_WORDS[i]}" in
            -*) continue ;;
        esac
        if [ "$seen" -eq 0 ]; then
            command="${COMP_WORDS[i]}"
            seen=1
        elif [ -z "$sub" ]; then
            sub="${COMP_WORDS[i]}"
        fi
    done

    if [ -z "$command" ]; then
        mapfile -t COMPREPLY < <(compgen -W "$commands" -- "$cur")
        return
    fi

    if [[ "$cur" == -* ]]; then
        case "$command" in
            audit) flags="--json --n --raw --since --state-dir" ;;
            bundle) flags="--engine-version --o --output --state-dir" ;;
            cache) flags="--insecure --json --keep-data --port --state-dir --upstream" ;;
            compact) flags="--distro --dry-run --json --no-trim --restart --state-dir --wait" ;;
            config) flags="--json --state-dir" ;;
            doctor) flags="--fix --json --report --state-dir" ;;
            enable-gpu) flags="--distro --off --state-dir --vendor" ;;
            healthcheck) flags="--json --state-dir --wait" ;;
            install) flags="--config --data-dir --distro --engine-version --headless --json --locked --no-autostart --no-verify-signature --offline --rootfs-sha256 --rootfs-url --state-dir" ;;
            lock) flags="--engine-version --o --output" ;;
            logs) flags="--follow --json --n --source --state-dir" ;;
            migrate) flags="--docker --docker-host --dry-run --from-context --from-desktop --from-host --from-podman --from-rancher --only --state-dir" ;;
            prewarm) flags="--concurrency --json" ;;
            profile) flags="--json --state-dir" ;;
            proxy) flags="--distro --no-context --no-path-translation --pipe --sddl --socket --state-dir" ;;
            prune) flags="--all --build-cache --json --until --volumes" ;;
            relocate) flags="--distro --dry-run --json --keep-archive --restart --state-dir" ;;
            remote) flags="--certs --host --json --state-dir" ;;
            reset) flags="--json --state-dir --to" ;;
            restart) flags="--state-dir --supervisor --timeout" ;;
            runner) flags="--json --state-dir" ;;
            serve) flags="--distro --state-dir --tcp" ;;
            snapshot) flags="--force --json --state-dir --yes" ;;
            start) flags="--state-dir --timeout" ;;
            status) flags="--json --prometheus --state-dir --stats" ;;
            stop) flags="--state-dir --supervisor --timeout" ;;
            supervise) flags="--distro --no-context --pipe --state-dir" ;;
            top) flags="--interval --json --once --state-dir" ;;
            uninstall) flags="--distro --state-dir --yes" ;;
            upgrade) flags="--apply --check --dry-run --force --json --offline --state-dir --timeout --yes" ;;
            wsl-integrate) flags="--remove --state-dir" ;;
            version) flags="--json --state-dir" ;;
            *) flags="" ;;
        esac
        mapfile -t COMPREPLY < <(compgen -W "$flags" -- "$cur")
        return
    fi

    # Values only the machine knows. Read-only, none starts the engine.
    #
    # Parsed from --json rather than the human listings: those carry an active
    # marker, and their "no profiles yet" sentence is a sentence, so text
    # parsing offered "no" as a completion. Without a JSON parser to hand this
    # uses grep for the name fields, which is enough for a flat list of names
    # and avoids making jq a requirement.
    local dynamic=""
    _skrog_names() { grep -o '"name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"\([^"]*\)"$/\1/'; }
    case "$command $sub" in
        "config get"|"config set")
            dynamic=$(skrog config --json 2>/dev/null \
                | sed -n '/"settings"/,$p' \
                | grep -o '"[a-z][a-z0-9.-]*"[[:space:]]*:' | sed 's/"\(.*\)"[[:space:]]*:/\1/') ;;
        "profile switch"|"profile show"|"profile delete")
            dynamic=$(skrog profile --json 2>/dev/null | _skrog_names) ;;
        "snapshot restore"|"snapshot delete")
            dynamic=$(skrog snapshot list --json 2>/dev/null | _skrog_names) ;;
        "remote use")
            dynamic="local $(skrog remote --json 2>/dev/null | _skrog_names)" ;;
        "remote test"|"remote remove")
            dynamic=$(skrog remote --json 2>/dev/null | _skrog_names) ;;
    esac
    if [ -n "$dynamic" ]; then
        mapfile -t COMPREPLY < <(compgen -W "$dynamic" -- "$cur")
        return
    fi

    if [ -z "$sub" ]; then
        case "$command" in
            audit) subs="tail trace" ;;
            autostart) subs="enable disable status" ;;
            cache) subs="enable disable status" ;;
            cli) subs="install status uninstall" ;;
            config) subs="get set export" ;;
            engine) subs="list upgrade rollback" ;;
            policy) subs="show check test" ;;
            profile) subs="list create switch show delete" ;;
            remote) subs="list add use test remove" ;;
            runner) subs="check" ;;
            serve) subs="cert" ;;
            snapshot) subs="list save restore delete" ;;
            wsl-config) subs="show apply" ;;
            *) subs="" ;;
        esac
        mapfile -t COMPREPLY < <(compgen -W "$subs" -- "$cur")
    fi
}

complete -F _skrog skrog
complete -F _skrog skrog.exe
