# skrog completions for PowerShell.
#
# GENERATED by scripts/build-completions.ps1 from the binary's own --help.
# Do not edit: CI regenerates this and fails if it differs.
#
# Install by dot-sourcing from your profile ($PROFILE):
#   . path\to\skrog.ps1
# Or, if skrog is on PATH, append it once:
#   skrog completions powershell >> $PROFILE     # not a command yet -- copy the file

$script:SkrogCommands = @(
    'audit'
    'autostart'
    'bundle'
    'cache'
    'cli'
    'compact'
    'config'
    'doctor'
    'enable-gpu'
    'engine'
    'healthcheck'
    'install'
    'lock'
    'logs'
    'migrate'
    'prewarm'
    'policy'
    'profile'
    'proxy'
    'prune'
    'relocate'
    'remote'
    'reset'
    'restart'
    'runner'
    'serve'
    'snapshot'
    'start'
    'status'
    'stop'
    'supervise'
    'uninstall'
    'upgrade'
    'wsl-integrate'
    'wsl-config'
    'version'
)

$script:SkrogSubcommands = @{
    'audit' = @('tail', 'trace')
    'autostart' = @('enable', 'disable', 'status')
    'cache' = @('enable', 'disable', 'status')
    'cli' = @('install', 'status', 'uninstall')
    'config' = @('get', 'set', 'export')
    'engine' = @('list', 'upgrade', 'rollback')
    'policy' = @('show', 'check', 'test')
    'profile' = @('list', 'create', 'switch', 'show', 'delete')
    'remote' = @('list', 'add', 'use', 'test', 'remove')
    'runner' = @('check')
    'serve' = @('cert')
    'snapshot' = @('list', 'save', 'restore', 'delete')
    'wsl-config' = @('show', 'apply')
}

$script:SkrogFlags = @{
    'audit' = @('--json', '--n', '--raw', '--since', '--state-dir')
    'bundle' = @('--engine-version', '--o', '--output', '--state-dir')
    'cache' = @('--json', '--keep-data', '--port', '--state-dir', '--upstream')
    'compact' = @('--distro', '--dry-run', '--json', '--no-trim', '--restart', '--state-dir', '--wait')
    'config' = @('--json', '--state-dir')
    'doctor' = @('--fix', '--json', '--report', '--state-dir')
    'enable-gpu' = @('--distro', '--off', '--state-dir', '--vendor')
    'healthcheck' = @('--json', '--state-dir', '--wait')
    'install' = @('--agent', '--config', '--data-dir', '--distro', '--engine', '--engine-version', '--headless', '--json', '--locked', '--no-autostart', '--no-verify-signature', '--offline', '--rootfs-sha256', '--rootfs-url', '--state-dir')
    'lock' = @('--engine-version', '--o', '--output')
    'logs' = @('--follow', '--json', '--n', '--source', '--state-dir')
    'migrate' = @('--docker', '--docker-host', '--dry-run', '--from-context', '--from-desktop', '--from-host', '--from-podman', '--from-rancher', '--only', '--state-dir')
    'prewarm' = @('--concurrency', '--json')
    'profile' = @('--json', '--state-dir')
    'proxy' = @('--agent', '--distro', '--engine', '--no-context', '--no-path-translation', '--pipe', '--sddl', '--socket', '--state-dir')
    'prune' = @('--all', '--build-cache', '--json', '--until', '--volumes')
    'relocate' = @('--distro', '--dry-run', '--json', '--keep-archive', '--restart', '--state-dir')
    'remote' = @('--certs', '--host', '--json', '--state-dir')
    'reset' = @('--json', '--state-dir', '--to')
    'restart' = @('--state-dir', '--supervisor', '--timeout')
    'runner' = @('--json', '--state-dir')
    'serve' = @('--distro', '--state-dir', '--tcp')
    'snapshot' = @('--force', '--json', '--state-dir', '--yes')
    'start' = @('--state-dir', '--timeout')
    'status' = @('--json', '--prometheus', '--state-dir', '--stats')
    'stop' = @('--state-dir', '--timeout')
    'supervise' = @('--agent', '--distro', '--no-context', '--pipe', '--state-dir')
    'uninstall' = @('--distro', '--state-dir', '--yes')
    'upgrade' = @('--apply', '--check', '--dry-run', '--force', '--json', '--offline', '--state-dir', '--timeout', '--yes')
    'wsl-integrate' = @('--remove', '--state-dir')
    'version' = @('--json', '--state-dir')
}

# Values that only the machine knows: config keys, saved profiles, registered
# remotes, snapshots. Asking skrog at completion time beats baking a list that
# is wrong the moment someone saves a profile.
#
# Every one of these goes through --json rather than parsing the human output:
# the text listings carry an active marker, and their "no profiles yet"
# sentence is a sentence, so text parsing offered "no" as a completion.
#
# All are read-only and none starts the engine. Failures are swallowed: a
# completion that throws is worse than one that offers nothing.
function Get-SkrogDynamic([string]$kind) {
    try {
        switch ($kind) {
            'config-key' {
                $j = & skrog config --json 2>$null | ConvertFrom-Json
                $j.settings.PSObject.Properties.Name
            }
            'profile'  { (& skrog profile --json 2>$null | ConvertFrom-Json).profiles.name }
            'remote'   { (& skrog remote --json 2>$null | ConvertFrom-Json).remotes.name }
            'snapshot' { (& skrog snapshot list --json 2>$null | ConvertFrom-Json).name }
        }
    } catch { @() }
}

Register-ArgumentCompleter -Native -CommandName skrog -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    # Everything before the cursor, minus the executable itself.
    $tokens = @($commandAst.CommandElements | Select-Object -Skip 1 |
        ForEach-Object { $_.ToString() })
    # The word being typed is not yet a settled token. The Count -eq 1 case is
    # separate on purpose: $tokens[0..-1] does not produce an empty array, it
    # wraps and yields the element twice, which made `skrog sn<TAB>` offer
    # nothing because "sn" looked like a settled command name.
    if ($wordToComplete -and $tokens.Count -gt 0 -and $tokens[-1] -eq $wordToComplete) {
        if ($tokens.Count -eq 1) { $tokens = @() }
        else { $tokens = $tokens[0..($tokens.Count - 2)] }
    }
    $positional = @($tokens | Where-Object { $_ -notlike '-*' })
    $command = if ($positional.Count -gt 0) { $positional[0] } else { $null }
    $sub = if ($positional.Count -gt 1) { $positional[1] } else { $null }

    $candidates = @()
    if (-not $command) {
        $candidates = $script:SkrogCommands
    } else {
        if ($wordToComplete -like '-*') {
            $candidates = $script:SkrogFlags[$command]
        } else {
            # A value position: offer what this machine actually has.
            $dynamic = switch ("$command $sub") {
                'config get'      { Get-SkrogDynamic 'config-key' }
                'config set'      { if ($positional.Count -le 2) { Get-SkrogDynamic 'config-key' } }
                'profile switch'  { Get-SkrogDynamic 'profile' }
                'profile show'    { Get-SkrogDynamic 'profile' }
                'snapshot restore' { Get-SkrogDynamic 'snapshot' }
                'snapshot delete' { Get-SkrogDynamic 'snapshot' }
                'remote use'      { @(Get-SkrogDynamic 'remote') + 'local' }
                'remote test'     { Get-SkrogDynamic 'remote' }
                default { $null }
            }
            if ($null -ne $dynamic) {
                $candidates = $dynamic
            } elseif (-not $sub) {
                $candidates = $script:SkrogSubcommands[$command]
            }
        }
    }

    $candidates |
        Where-Object { $_ -and $_.StartsWith($wordToComplete, [StringComparison]::OrdinalIgnoreCase) } |
        Sort-Object -Unique |
        ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
}
